[workspace]
members = [
    "coreutils_core",
    "basename",
    "dirname",
    "echo",
    "false",
    "groups",
    "id",
    "logname",
    "nice",
    "pwd",
    "seq",
    "sleep",
    "true",
    "whoami",
    "uname",
    "tty",
    "yes"
]
