[workspace]
members = [
    "coreutqils_core",
    "basename",
    "clear",
    "cut",
    "date",
    "dirname",
    "echo",
    "env",
    "false",
    "groups",
    "head",
    "id",
    "link",
    "logname",
    "mv",
    "pwd",
    "rm",
    "rmdir",
    "sleep",
    "true",
    "tty",
    "uname",
    "unlink",
    "wc",
    "whoami",
    "yes",
]
