unstable_features = true
version = "Two"
make_backup = true
indent_style = "Block"
binop_separator = "Front"
combine_control_expr = true
wrap_comments = true
comment_width = 90
condense_wildcard_suffixes = true
disable_all_formatting = false
fn_args_layout = "Compressed"
brace_style = "SameLineWhere"
empty_item_single_line = true
enum_discrim_align_threshold = 6
fn_single_line = true
where_single_line = true
force_explicit_abi = true
format_strings = true
format_macro_matchers = true
format_macro_bodies = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "Mixed"
merge_imports = true
match_block_trailing_comma = true
max_width = 100
merge_derives = true
force_multiline_blocks = false
newline_style = "Auto"
normalize_comments = true
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
reorder_impl_items = true
skip_children = false
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 6
spaces_around_ranges = false
struct_lit_single_line = true
tab_spaces = 4
trailing_comma = "Vertical"
trailing_semicolon = true
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
match_arm_blocks = true
overflow_delimited_expr = true
blank_lines_upper_bound = 3
blank_lines_lower_bound = 0
color = "Auto"
# license_template_path = "Copyright {\\y} Eric Shimizu Karbstein."
edition = "2018"
normalize_doc_attributes = true
inline_attribute_width = 0
use_small_heuristics = "Max"
ignore = [
    "coreutils_core/src/passwd.rs",
]
