[package]
name = "uniq"
version = "0.1.0"
authors = ["Jo√£o M. Bezerra <marcospb19@hotmail.com>"]
license = "MPL-2.0-no-copyleft-exception"
build = "build.rs"
edition = "2018"
description = """
Merge adjacent matching lines from INPUT (or standard input).
"""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "^2.33.0", features = ["wrap_help"] }

[build-dependencies]
clap = "^2.33.0"
