[package]
name = "time"
version = "0.2.0"
authors = ["Vaibhav Yenamandra <v@calloc.net>"]
license = "MPL-2.0-no-copyleft-exception"
build = "build.rs"
edition = "2018"
description = "Run COMMAND, then display the system resource usage."

[dependencies]
clap = { version = "^2.33.0", features = ["wrap_help"] }
coreutils_core = { path = "../coreutils_core" }
indoc = "^1.0"

[build-dependencies]
clap = { version = "^2.33.0" }
indoc = "^1.0"
